export const profiles= [
    {
        id: 1,
        name: "John Doe",
        photo:"https://placehold.co/100x100?text=John Doe",
        description: "Software Engineer",
        address: "Paud Road Kothrud",
    },
    {
    id: 2,
    name: "Jane Smith",
    photo: "https://placehold.co/100x100?text=Jane Smith",
    description: "Data Scientist",
    address: "Shvaji Nagar",
  },
  {
    id:3,
    name: "Hrishikesh Tarale",
    photo: "https://placehold.co/100x100?text=Hrishikesh",
    description: "Full Stack Developer",
    address: "Chandani Chowk",
  },
  {
    id:4,
    name: "Rahul Deshmukh",
    photo: "https://placehold.co/100x100?text=Rahul",
    description: "DevOps Engineer",
    address: "Pimpri chinchwad",
  },
  {
    id:5,
    name: "Prajwal Sayankar",
    photo: "https://placehold.co/100x100?text=Prajwal",
    description: "Network Engineer",
    address: "Hinjewadi",
  },
  {
    id:6,
    name: "Rohan Patil",
    photo: "https://placehold.co/100x100?text=Rohan",
    description: "Cloud Engineer",
    address: "Sinhgad Road",
  },
  {
    id:7,
    name: "Siddharth Kulkarni",
    photo: "https://placehold.co/100x100?text=Siddharth",
    description: "Cyber Security",
    address: "Kothrud",
  },
];
